name: Amuniym CI

on: 
  push:
    branches:    
      - master
      - 'releases/*'
    tags:
      - v1.0
jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Docker Login
      run: docker login -u engincanhoke -p 6UU5hfdn2nWAX3A
      shell: bash
    - name: Docker Image Build
      run: docker image build -t engincanhoke/githubci:latest .
      shell: bash
    - name: Docker Image Push
      run: docker push engincanhoke/githubci:latest
      shell: bash
    - name: Installations
      run: |
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add - && \
        sudo apt-get update && sudo apt-get install google-cloud-sdk && \
        curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && \
        chmod +x ./kubectl && \
        sudo mv ./kubectl /usr/local/bin/kubectl && \
        curl -L https://git.io/get_helm.sh | bash && \
        helm init --client-only 
      shell: bash
    - name: Helm deploy
      run: |
        helm upgrade helloworld hello-world --namespace application --set image.tag="latest" && \

#    - name: Deploy 4
#      run: curl -LO https://storage.googleapis.com/kubernetes-helm/helm-v2.14.1-linux-amd64.tar.gz  && tar -xvzf helm-v2.14.1-linux-amd64.tar.gz
#      shell: bash
#    - name: Deploy 5
#      run: mv linux-amd64/helm /usr/bin/ && chmod +x /usr/bin/helm
#      shell: bash
#    - name: Deploy 6
#      run: helm init --upgrade
#      shell: bash
#    - name: Deploy 7
#      run: helm version
#      shell: bash
#    - name: Deploy 8
#      run: helm upgrade --install production-backend-tarfin --namespace prod --set backend.image=$IMAGE_URL_PROD backend-deploy/
#      shell: bash
#     - name: Deploy
#       run: apk update && apk add curl
#       run: curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.6.0/bin/linux/amd64/kubectl
#       run: chmod +x ./kubectl && mv ./kubectl /usr/bin/kubectl
#       run: curl -LO https://storage.googleapis.com/kubernetes-helm/helm-v2.14.1-linux-amd64.tar.gz  && tar -xvzf helm-v2.14.1-linux-amd64.tar.gz
#       run: mv linux-amd64/helm /usr/bin/ && chmod +x /usr/bin/helm
#       run: helm init --upgrade
#       run: helm version
#       run: helm upgrade --install production-backend-tarfin --namespace prod --set backend.image=$IMAGE_URL_PROD backend-deploy/
#       shell: bash
