name: Amuniym CI

on: 
  push:
    branches:    
      - master
      - 'releases/*'
    tags:
      - v1.0

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: ls
      run: ls -al
      shell: bash
    - name: Docker Build
      run: docker image build -t engincanhoke/githubci:latest .
      shell: bash
    - name: Docker Login
      run: docker login -u engincanhoke -p 6UU5hfdn2nWAX3A
      shell: bash
    - name: Docker Push
      run: docker push engincanhoke/githubci:latest
      shell: bash
