name: Amuniym CI

on: 
  push:
    branches:    
      - master
      - 'releases/*'
    tags:
      - v1.0

jobs:
  build:

    runs-on: centos:7

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Docker Build
      run: docker image build -t springboot-helloworld .
      shell: bash
    - name: Docker Commit
      run: docker commit $(docker ps -a | grep gazgeek/springboot-helloworld | awk {'print $1'}) engincanhoke/springboot-helloworld-0.0.3-g
      shell: bash
    - name: Docker Login
      run: docker login -u engincanhoke -p 6UU5hfdn2nWAX3A
      shell: bash
    - name: Docker Push
      run: docker push engincanhoke/springboot-helloworld-0.0.3-g
      shell: bash
