name: Deneneeme CI

on: 
  push:
    branches:    
      - master
      - 'releases/*'
    tags:
      - v1.0
jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: ls
      run: |
        sudo apt-get update && \
        sudo apt-get install net-tools && \
        echo oldu
      shell: bash
